# --- Server ---
server.port=8089

# --- PostgreSQL Datasource ---

#   CREATE DATABASE hospital_appointments;
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_appointments
spring.datasource.username=postgres
spring.datasource.password=@3375#
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Jackson (for LocalDateTime serialization) ---
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
